name: CI

on:      
  workflow_dispatch:
    inputs:
      LION:
        type: boolean
        description: 🦁 LION
      RHINO:
        type: boolean
        description: 🦏 RHINO
      PIG:
        type: boolean
        description: 🐷 PIG
      PANDA:
        type: boolean
        description: 🐼 PANDA
      ALL:
        type: boolean
        description: ALL
      choice:
        type: choice
        description: Make a environment
        options:
         - DEV
         - PROD
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: greet
        run: | 
          echo "choice is ${{ github.event.inputs.choice }}"
  
  deploy-application:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    needs: check-application
    runs-on: ubuntu-latest
    steps:
    
    - name: Job to <<RHINO>>
      if: ${{  github.event.inputs.RHINO == 'true' || github.event.inputs.ALL == 'true' }}
      run: |
        echo "Log level: $NAMESPACE, env: $PROFILE"
      env:
        NAMESPACE: "RHINO"
        PROFILE: "${{ github.event.inputs.choice }}"

    - name: Job to <<LION>>
      if: ${{ github.event.inputs.LION == 'true' || github.event.inputs.ALL == 'true' }}
      run: |
        echo "Log level: $NAMESPACE, env: $PROFILE"
      env:
        NAMESPACE: "LION"
        PROFILE: "${{ github.event.inputs.choice }}"

    - name: Job to <<PIG>>
      if: ${{ github.event.inputs.PIG == 'true' || github.event.inputs.ALL == 'true' }}
      run: |
        echo "Log level: $NAMESPACE, env: $PROFILE"
      env:
        NAMESPACE: "PIG"
        PROFILE: "${{ github.event.inputs.choice }}"
  
    - name: Job to <<PANDA>>
      if: ${{ github.event.inputs.PANDA == 'true' || github.event.inputs.ALL == 'true' }}
      run: |
        echo "Log level: $NAMESPACE, env: $PROFILE"
      env:
        NAMESPACE: "PANDA"
        PROFILE: "${{ github.event.inputs.choice }}"
