name: CI

on:
  push:
    branches:
      - main
      
  workflow_dispatch:
    inputs:
      LION:
        type: boolean
        description: LION
      RHINO:
        type: boolean
        description: RHINO
      choice:
        type: choice
        description: Make a choice
        options:
         - RHINO
         - LION
         - HIPPO
         - PANDA
         - ALL
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: greet
        run: | 
          echo "choice is ${{ github.event.inputs.choice }}"
  
  deploy-application:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    needs: check-application
    runs-on: ubuntu-latest
    steps:
    
    - name: Job to <<RHINO>>
      if: ${{ github.event.inputs.choice == 'RHINO' || github.event.inputs.choice == 'ALL' }}
      run: |
        echo "Log level: $NAMESPACE"
      env:
        NAMESPACE: "RHINO"

    - name: Job to <<LION>>
      if: ${{ github.event.inputs.choice == 'LION' || github.event.inputs.choice == 'ALL' }}
      run: |
        echo "Log level: $NAMESPACE"
      env:
        NAMESPACE: "LION"

    - name: Job to <<HIPPO>>
      if: ${{ github.event.inputs.choice == 'HIPPO' || github.event.inputs.choice == 'ALL' }}
      run: |
        echo "Log level: $NAMESPACE"
      env:
        NAMESPACE: "HIPPO"
  
    - name: Job to <<PANDA>>
      if: ${{ github.event.inputs.choice == 'PANDA' || github.event.inputs.choice == 'ALL' }}
      run: |
        echo "Log level: $NAMESPACE"
      env:
        NAMESPACE: "PANDA"
