name: CI

on:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: Make a choice
        options:
        - NAMESPACE A
        - NAMESPACE B
        - NAMESPACE C
        - NAMESPACE D
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: greet
        run: | 
          echo "choice is ${{ github.event.inputs.choice }}"
